stanford_publication_import alpha1 review
SU-SWS/stanford_publication_import pull request #1
Opened 2021-09-21 15:50 UTC by ksharp-drupal

# READY FOR REVIEW

# Summary
- Initial (alpha1) version of Stanford Publication Import module for CSV imports
- Needs to be reviewed and tested as part of SWS D9 sites stack.

# Review By (Date)
- Before D7 sites go away.

# Things to consider
- Module was created based on stanford_module_example repository. Some of the untouched files are different from those in stanford_publications, so please take a look at those.
- Developed using Stanford Earth se3_blt D8 project, but code should be D9-ready.
- Depends on stanford_publications, migrate, migrate_plus, migrate_tools, migrate_file, migrate_source_csv modules
- Includes a sample CSV file; CSV file details are in README
- I needed to patch entity_reference_revisions module to successfully create a paragraph_row wysiwyg paragraph using the following:
- I found that I needed these patches to import body text into components:
 * Requires the following patches to the entity_reference_revisions module
 * https://www.drupal.org/files/issues/migrate_import_fatal-2843278-5.patch
 * https://www.drupal.org/files/issues/2020-04-14/allow_scalar_values-2667748-D8-41.patch
 * see:
 * https://www.drupal.org/project/entity_reference_revisions/issues/2843278
 * https://www.drupal.org/project/entity_reference_revisions/issues/2667748
- Once installed, test at /admin/stanford_publication_import_csv; test rollback using migration menu

2021-09-21 21:11 UTC, pookmish requested changes
There's alot of this that is either a, not needed or b, that needs to be done a different way. Also it would be best to put all of this functionality as a submodule of the [stanford_publication](https://github.com/SU-SWS/stanford_publication/) module.

2021-09-21 21:11 UTC, pookmish commented on src/Form/StanfordPublicationImportFromCsv.php
> +class StanfordPublicationImportFromCsv extends ConfigSingleImportForm {
This might have been the solution for Earth, but this won't be a valid approach for the core product. The `stanford_migrate` module already provides a form for uploading the csv file if the migration exists.

2021-09-21 21:11 UTC, pookmish commented on src/Plugin/migrate/process/StanfordPublicationImportCitation.php
> +class StanfordPublicationImportCitation extends ProcessPluginBase {
This could all be accomplished using the migration configuration. There's no need for a migration plugin.

2021-09-21 21:11 UTC, pookmish commented on src/Plugin/migrate/process/StanfordPublicationImportComponent.php
> +class StanfordPublicationImportComponent extends ProcessPluginBase {
This doesn't have proper dependency injection and i believe there would be an easier way to accomplish this using the migration configuration.

2021-09-24 15:15 UTC, closed without merging

2021-09-24 15:16 UTC, ksharp-drupal commented
Withdrawn